### ISSUE TITLE
Stretch top header 

### ISSUE THREAD

**Issue by vlascik** [cfoellmann/github-wide#11]
Top header isn't stretched to full width with this style, when used with Octotree, this causes a problem. See https://github.com/buunguyen/octotree/issues/497
Can be fixed by adding
```
.container-lg {
	max-width: inherit !important;
}
```

**Comment by cfoellmann** [comment]
the "original" github-wide style doesn't have this issue with octotree. In the referenced post a chrome extension named 'github-wide' is used.
