### ISSUE TITLE
User profile photo is stretched

### ISSUE THREAD

**Issue by snowe2010** [cfoellmann/github-wide#14]
Title^ 

The user profile photo stretches to a strange aspect ratio, causing the image to distort.

**Comment by cfoellmann** [comment]
have updated the style in your browser?
I put up a new version today and that has the fix for it.

Also @mdo is starting on a version 2 achieving everything current and more. Hopefully soon

**Comment by snowe2010** [comment]
Oh? Haha! No I hadn't updated. That fixed it! 

There's also an issue with the Discover tab on the main page. I'm guessing he'll resolve that as well?

**Comment by snowe2010** [comment]
It doesn't seem to be using the full width, but that's probably fine. 

![screenshot 2018-07-19 13 31 31](https://user-images.githubusercontent.com/1534535/42965775-1c679c44-8b58-11e8-9e4a-e0e1570a36cc.png)

**Comment by cfoellmann** [comment]
Yes. Everything will be new and I think it will need testing and feedback then

**Comment by cfoellmann** [comment]
Testing https://github.com/mdo/github-wide/pull/49 would help @mdo out
